name = "convex_eval"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ConvexEval"]
lintDriver = "mathlib4/lint"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "f897ebcf72cd16f89ab4577d0c826cd14afaafc7"
scope = "leanprover-community"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "ConvexEval"
